#!/usr/bin/python
#
# This script generates a simple HTML page (via STDOUT) including tables for the data generated by join_csvs.py script.
# Each table will contain 3 x 2 colums, that is, 3 columns per CSV file (currently only 2 CSV files are supported).
#
# The resulting table is something like:
#    name_CSV1,cred_CSV1,name_cred_CSV2
#    jlcanovas,23.21,jcabo,22.33
#
# It helps to visualize and compare the cred variations between graphs with different weights
#
# Author: Javier Canovas (me@jlcanovas.es)
#

import csv
import sys

files = [
    # Set here the name of the projects to consider (e.g., "d3/d3")
]

# These variables are use to locate the CSV file
# The script will look for PREFFIX + files[i] + SUFFIX1 and then for PREFFIX + files[i] + SUFFIX2
PREFFIX = "credResult_"
SUFFIX1 = "_CODERS.csv"
SUFFIX2 = "_COMMENTERS.csv"

# Number of row to list in each table
TABLE_SIZE = 10

# Generating the website (quite adhoc)
print('<!DOCTYPE html><html><head></head>')
print('<style>')
print('table { border: 1px solid black; margin-right: auto; margin-left: auto; margin-top: 15px;}')
print('th { padding: 5px 10px 5px 10px; text-align: center; border-bottom: 1px solid #000000; }')
print('td { padding: 5px 10px 5px 10px; text-align: left; border-bottom: 1px solid #ddd; }')
print('</style>')
print('<body>')

# For each project to consider
for file in files:
    # Getting first CSV file
    coders_csv_path = PREFFIX + file + SUFFIX1
    coders_tuplelist = []
    with open(coders_csv_path, newline='') as csv1_file:
        csv1_reader = csv.reader(csv1_file, delimiter=',')
        for row in csv1_reader:
            if row[2] == "USERLIKE":
                coders_tuplelist.append(tuple(row))
    # Ordering the csv data according to cred column
    coder_sorted = sorted(coders_tuplelist, key=lambda r: float(r[1]), reverse=True)

    # Getting second CSV file
    commenters_csv_path = PREFFIX + file + SUFFIX2
    commenters_tuplelist = []
    with open(commenters_csv_path, newline='') as csv2_file:
        csv2_reader = csv.reader(csv2_file, delimiter=',')
        for row in csv2_reader:
            if row[2] == "USERLIKE":
                commenters_tuplelist.append(tuple(row))
    # Ordering the csv data according to cred column
    commenters_sorted = sorted(commenters_tuplelist, key=lambda r: float(r[1]), reverse=True)

    # Printing the table for this couple of CSVs
    print('<table>')
    print(f'<tr><th colspan="4">{file}</th></tr>')
    print('<tr><th>Username</th><th>Coder Cred</th><th>Username</th><th>Commenter Cred</th></tr>')
    for i in range(0, TABLE_SIZE):
        print(f'<tr><td>{coder_sorted[i][3]}</td><td>{coder_sorted[i][1]}</td><td>{commenters_sorted[i][3]}</td><td>{commenters_sorted[i][1]}</td>')
    print('</table>')
print('</body>')